"""Resource pack generation from translated lang files."""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

LogFn = Optional[Callable[[str], None]]

LATEST_PACK_FORMAT = 99
PACK_DESCRIPTION = "Generated by MCModLocalizer"
# テンプレートから複製しないファイル（生成時に別途用意するため）
_SKIP_TEMPLATE_NAMES = {"pack.mcmeta", "pack.png"}


def collect_pack_translations(base_dir: Path) -> Dict[str, Path]:
    """base_dir 以下の ja_jp.json を {modid: path} として収集する。"""
    translations: Dict[str, Path] = {}
    if not base_dir.exists() or not base_dir.is_dir():
        return translations
    try:
        for candidate in base_dir.rglob("ja_jp.json"):
            if not candidate.is_file():
                continue
            parent = candidate.parent
            if parent.name == "lang" and parent.parent != parent:
                translations[parent.parent.name] = candidate
            else:
                translations[parent.name] = candidate
    except Exception:
        return translations
    return translations


class ResourcePackBuilder:
    """翻訳済み ja_jp.json 群から Minecraft リソースパックを生成する。"""

    def __init__(
        self,
        template_dir: Path,
        icon_path: Optional[Path] = None,
        *,
        log: LogFn = None,
    ) -> None:
        self.template_dir = template_dir
        self.icon_path = icon_path
        self._log = log

    def _emit(self, msg: str) -> None:
        if self._log:
            self._log(msg)

    def build(self, output_dir: Path, produced: List[Tuple[str, Path]]) -> Optional[Path]:
        """produced (modid, ja_jp.json パス) からリソースパックを生成し、その場所を返す。"""
        if not produced:
            return None
        self._emit("[INFO] リソースパック生成を開始します。")

        # リソースパック名は「出力先(resourcepacks)の親フォルダ名_localize」とする
        # 例: .../MyModPack/resourcepacks -> MyModPack_localize
        try:
            base_name = output_dir.parent.name
        except Exception:
            base_name = "ModPack"
        if not base_name:
            base_name = "ModPack"

        pack_dir = output_dir / f"{base_name}_localize"
        pack_dir.mkdir(parents=True, exist_ok=True)
        self._apply_template_files(pack_dir)

        assets_dir = pack_dir / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)
        for modid, ja_path in produced:
            target_dir = assets_dir / modid / "lang"
            target_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ja_path, target_dir / "ja_jp.json")

        self._write_pack_mcmeta(pack_dir)
        self._ensure_icon(pack_dir)
        return pack_dir

    def _write_pack_mcmeta(self, pack_dir: Path) -> None:
        pack_meta = {
            "pack": {
                "pack_format": LATEST_PACK_FORMAT,
                "supported_formats": {
                    "edition": "java",
                    "min_inclusive": 1,
                    "max_inclusive": LATEST_PACK_FORMAT,
                },
                "description": PACK_DESCRIPTION,
            }
        }
        pack_dir.mkdir(parents=True, exist_ok=True)
        (pack_dir / "pack.mcmeta").write_text(
            json.dumps(pack_meta, ensure_ascii=False, indent=2), encoding="utf-8"
        )

    def _apply_template_files(self, pack_dir: Path) -> None:
        if not self.template_dir.exists():
            return
        for item in self.template_dir.iterdir():
            if item.name in _SKIP_TEMPLATE_NAMES:
                continue
            target = pack_dir / item.name
            if item.is_dir():
                shutil.copytree(item, target, dirs_exist_ok=True)
            elif item.is_file():
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(item, target)

    def _ensure_icon(self, pack_dir: Path) -> None:
        pack_png = pack_dir / "pack.png"
        if pack_png.exists():
            return
        if not self.icon_path or not self.icon_path.exists():
            self._emit(f"[WARN] icon.png が見つかりません: {self.icon_path}")
            return
        try:
            shutil.copy2(self.icon_path, pack_png)
        except Exception as e:
            self._emit(f"[WARN] アイコンのコピーに失敗しました: {e}")


__all__ = ["ResourcePackBuilder", "collect_pack_translations"]
