"""Regression tests for ResourcePackBuilder and collect_pack_translations."""
from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from app.services.resource_pack import ResourcePackBuilder, collect_pack_translations


class ResourcePackBuilderTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        # template dir with one normal file and a pack.png that must be skipped
        self.tpl = self.root / "tpl"
        self.tpl.mkdir()
        (self.tpl / "credits.txt").write_text("hi", encoding="utf-8")
        (self.tpl / "pack.png").write_text("TEMPLATE_PNG", encoding="utf-8")
        # bundled icon
        self.icon = self.root / "icon.png"
        self.icon.write_bytes(b"\x89PNG")
        # produced ja_jp.json
        self.ja = self.root / "src" / "examplemod" / "ja_jp.json"
        self.ja.parent.mkdir(parents=True)
        self.ja.write_text(json.dumps({"a": "あ"}, ensure_ascii=False), encoding="utf-8")
        # output dir: .../MyPack/resourcepacks -> pack name MyPack_localize
        self.out = self.root / "MyPack" / "resourcepacks"
        self.out.mkdir(parents=True)

    def tearDown(self):
        self._tmp.cleanup()

    def _build(self):
        builder = ResourcePackBuilder(template_dir=self.tpl, icon_path=self.icon)
        return builder.build(self.out, [("examplemod", self.ja)])

    def test_pack_name_from_parent_dir(self):
        pack = self._build()
        self.assertIsNotNone(pack)
        self.assertEqual(pack.name, "MyPack_localize")

    def test_lang_file_copied(self):
        pack = self._build()
        copied = pack / "assets" / "examplemod" / "lang" / "ja_jp.json"
        self.assertTrue(copied.exists())
        self.assertEqual(json.loads(copied.read_text(encoding="utf-8")), {"a": "あ"})

    def test_mcmeta_written(self):
        pack = self._build()
        meta = json.loads((pack / "pack.mcmeta").read_text(encoding="utf-8"))
        self.assertEqual(meta["pack"]["pack_format"], 99)
        self.assertEqual(meta["pack"]["description"], "Generated by MCModLocalizer")

    def test_template_applied_but_packpng_skipped(self):
        pack = self._build()
        self.assertEqual((pack / "credits.txt").read_text(encoding="utf-8"), "hi")
        # template pack.png must NOT win; bundled icon is used instead
        self.assertEqual((pack / "pack.png").read_bytes(), b"\x89PNG")

    def test_empty_produced_returns_none(self):
        builder = ResourcePackBuilder(template_dir=self.tpl, icon_path=self.icon)
        self.assertIsNone(builder.build(self.out, []))


class CollectPackTranslationsTest(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)

    def tearDown(self):
        self._tmp.cleanup()

    def test_keys_by_modid_under_lang(self):
        ja = self.root / "assets" / "examplemod" / "lang" / "ja_jp.json"
        ja.parent.mkdir(parents=True)
        ja.write_text("{}", encoding="utf-8")
        found = collect_pack_translations(self.root)
        self.assertIn("examplemod", found)
        self.assertEqual(found["examplemod"], ja)

    def test_missing_dir_returns_empty(self):
        self.assertEqual(collect_pack_translations(self.root / "nope"), {})


if __name__ == "__main__":
    unittest.main()
